"""
LoveAdvisor V3 - Enumeration Types
Phase 1: Engineering Skeleton Initialization

This module defines enumeration types used throughout the LoveAdvisor V3 system.
Using enums improves type safety, documentation, and maintainability.
"""

from enum import Enum


class PipelineStage(str, Enum):
    """
    Pipeline stages in the LoveAdvisor V3 analysis pipeline.

    Each stage corresponds to a distinct phase of processing:
    - PREPROCESS: Clean and enrich user input
    - SIGNAL_EXTRACTION: Extract emotional and relational signals
    - STRATEGY_GENERATION: Generate advice and strategies
    - OUTPUT_BUILDING: Format results and apply guardrails
    - HISTORY_LOGGING: Store results for future reference
    """
    PREPROCESS = "preprocess"
    SIGNAL_EXTRACTION = "signal_extraction"
    STRATEGY_GENERATION = "strategy_generation"
    OUTPUT_BUILDING = "output_building"
    HISTORY_LOGGING = "history_logging"


class SignalType(str, Enum):
    """
    Types of emotional and relational signals extracted from user input.

    These signals form the foundation for strategy generation and are
    categorized based on the aspect of relationships they address.
    """
    # Emotional signals
    EMOTIONAL_STATE = "emotional_state"  # Happiness, sadness, anger, etc.
    EMOTIONAL_INTENSITY = "emotional_intensity"  # Low, medium, high
    EMOTIONAL_VALENCE = "emotional_valence"  # Positive, negative, neutral

    # Relational signals
    RELATIONSHIP_STAGE = "relationship_stage"  # Dating, committed, married, etc.
    RELATIONSHIP_QUALITY = "relationship_quality"  # Healthy, toxic, improving, etc.
    COMMUNICATION_PATTERN = "communication_pattern"  # Open, avoidant, aggressive, etc.
    CONFLICT_STYLE = "conflict_style"  # Constructive, destructive, avoidant

    # Behavioral signals
    ATTACHMENT_STYLE = "attachment_style"  # Secure, anxious, avoidant
    LOVE_LANGUAGE = "love_language"  # Words, acts, gifts, time, touch
    NEEDS_EXPRESSED = "needs_expressed"  # Safety, connection, autonomy, etc.

    # Contextual signals
    CULTURAL_CONTEXT = "cultural_context"  # Cultural norms and expectations
    GENDER_DYNAMICS = "gender_dynamics"  # Gender roles and expectations
    POWER_BALANCE = "power_balance"  # Equality, imbalance, manipulation


class StrategyType(str, Enum):
    """
    Types of strategies generated by the LoveAdvisor system.

    Strategies are actionable recommendations tailored to the user's
    specific situation and extracted signals.
    """
    # Communication strategies
    ACTIVE_LISTENING = "active_listening"
    I_STATEMENTS = "i_statements"
    NONVIOLENT_COMMUNICATION = "nonviolent_communication"
    BOUNDARY_SETTING = "boundary_setting"

    # Emotional regulation strategies
    EMOTION_LABELING = "emotion_labeling"
    MINDFULNESS = "mindfulness"
    COGNITIVE_REFRAMING = "cognitive_reframing"
    SELF_COMPASSION = "self_compassion"

    # Relationship building strategies
    QUALITY_TIME = "quality_time"
    APPRECIATION_EXPRESSION = "appreciation_expression"
    CONFLICT_RESOLUTION = "conflict_resolution"
    FUTURE_PLANNING = "future_planning"

    # Safety strategies
    EXIT_STRATEGY = "exit_strategy"
    SUPPORT_SEEKING = "support_seeking"
    PROFESSIONAL_HELP = "professional_help"
    SAFETY_PLANNING = "safety_planning"


class OutputFormat(str, Enum):
    """
    Formats for presenting analysis results.

    Different formats may be used for different presentation contexts
    (e.g., API responses, frontend display, debugging).
    """
    STRUCTURED = "structured"  # Detailed structured JSON
    CONCISE = "concise"  # Simplified summary for display
    ACTIONABLE = "actionable"  # Step-by-step action items
    DEBUG = "debug"  # Full debugging information


class LLMProvider(str, Enum):
    """
    Supported LLM providers.

    The system can work with multiple LLM providers, with the ability
    to switch between them based on configuration, cost, or performance.
    """
    DEEPSEEK = "deepseek"
    OPENAI = "openai"
    MOCK = "mock"  # For testing and development


class GuardrailSeverity(str, Enum):
    """
    Severity levels for guardrail violations.

    Determines how violations are handled (log, warn, block, etc.).
    """
    INFO = "info"  # Informational note, no action required
    WARNING = "warning"  # Potential issue, may require adjustment
    BLOCKING = "blocking"  # Serious issue, pipeline should be stopped
    SAFETY_CRITICAL = "safety_critical"  # Immediate safety concern